/*
Copyright (c) 2025 Kenneth MacCallum

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/


//*******************************************************************************************
//Includes
//*******************************************************************************************
#include <blueberry-receiver.h>

#include <stddef.h>

#include <brPacket.h>

//*******************************************************************************************
//Defines
//*******************************************************************************************

//*******************************************************************************************
//Types
//*******************************************************************************************

//*******************************************************************************************
//Variables
//*******************************************************************************************

//*******************************************************************************************
//Function Prototypes
//*******************************************************************************************

//*******************************************************************************************
//Code
//*******************************************************************************************

/**
 * Receive n bytes from the queue.
 * If the queue has less than n bytes available, then only use what is available.
 * This is intended for use with a UART
 * This function will test the CRC
 * This function will discard bytes from the queue if they are bad
 * This is implemented with function pointers. I tried to avoid them but it allows easy inclusion into the autogenerated code
 * the length field of the Bb packet field is used as a state variable. Zero indicates the state is reset. After that it indicates how many bytes have been successfully received
 * @param bb - the buffer for this packet, also the state of the receive routine
 * @param q - the queue that the new bytes are coming from
 * @param n - the maximum number of bytes to process - this is to limit the type that this routine will take at one calling
 * @param startWordCheck - a function to test the start word of the packet. It will check only up to the Bb.length. It should return true so long as the start word is good
 * @param lengthCheck - a function to test the length of the received packet so far. It should return true when enough bytes have been received
 * @param crcCheck - a function to check the CRC of the received bytes. It will return true with a correct match
 * @return true if a valid packet was received
 *
 */
bool blueberryReceive(Bb* bb, ByteQ* q, uint32_t n, CheckFunction startWordCheck, CheckFunction lengthCheck, CheckFunction crcCheck){
	bool result = false;
	bool fail = false;
	if( bb->length == 0){
		bb->buffer = q->buffer;
		bb->bufferLength = q->bufferSize;
		bb->start = q->front;

	}

	uint32_t m = getBytesUsed(q);
	if(m > n){
		m = n;
	}

	//cycle through all the bytes so far
	for(uint32_t i = 0; i < m; ++i){

		++(s->packet.length);

		if(startWordCheck(bb)){
			if(lengthCheck(bb)){
				if(crcCheck(bb)){
					result = true;
					break;
				} else {
					fail = true;
				}
			}
		} else {
			fail = true;
		}
		if(fail){
			discardFromByteQ(q, bb->length);
			bb->length = 0;
			bb->start = q->front;
		}
	}

	return result;

}
/**
 * Receive all bytes from the queue, or as many as is necessary to receive the packet
 * Assumes that the packet starts at the beginning of the queue
 * This is indended for use with ethernet
 * This function will not test the CRC
 * This function will discard the queue contents if the packet fails the checks
 * This is implemented with function pointers. I tried to avoid them but it allows easy inclusion into the autogenerated code
 * @param bb - the buffer for this packet, also the state of the receive routine
 * @param q - the queue that the new bytes are coming from
 * @param n - the maximum number of bytes to process - this is to limit the type that this routine will take at one calling
 * @param startWordCheck - a function to test the start word of the packet. It will check only up to the Bb.length. It should return true so long as the start word is good
 * @param lengthCheck - a function to test the length of the received packet so far. It should return true when enough bytes have been received and also populate the length field of the packet
 * @return true if a valid packet was received
 */
bool blueberryReceiveAll(Bb* bb, ByteQ* q, PacketCheck startWordCheck, PacketCheck lengthCheck){
	bool result = false;
	bb->buffer = q->buffer;
	bb->bufferLength = q->bufferSize;
	bb->start = q->front;
	uint32_t n = getBytesUsed(q);
	bb->length = n; //this field will eventually be set by the length check
	if(startWordCheck(bb)){
		if(lengthCheck(bb)){
			result = true;
		}
	}

	if(!result){
		//throw out the queue contents - the packet was no good
		discardFromByteQ(q, n);
	}

	return result;


}
/**
 * Free up data from the byte queue and prep the state
 */
void blueberryReceiveDone(Bb* bb, ByteQ* q){
	discardFromByteQ(q, bb->length);
	bb->rxTime = 0;
	bb->length = 0;
	bb->bufferLength = 0;
	bb->start = 0;
	bb->buffer = NULL;


}

bool blueberryReceive(BlueberryRecieveState* s, ByteQ* q, uint32_t startWord, uint32_t length, )


bool brPacketCheckBb(Bb* buf){

}
