/*
Copyright (c) 2025 Kenneth MacCallum

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/


//*******************************************************************************************
//Includes
//*******************************************************************************************
#include <blueberry-receiver.h>
#include <blueberry-transcoder.h>

#include <stddef.h>

#include <timeSync.h>
//#include <fastcodeUtil.h>

//*******************************************************************************************
//Defines
//*******************************************************************************************
#define PACKET_PREAMBLE (0x45554c42)
#define PACKET_LENGTH_INDEX (4)
#define PACKET_CRC_INDEX (6)
#define PACKET_PREAMBLE_INDEX (0)
#define PACKET_FIRST_MESSAGE_INDEX (8)
//*******************************************************************************************
//Types
//*******************************************************************************************

//*******************************************************************************************
//Variables
//*******************************************************************************************
//*******************************************************************************************
//Function Prototypes
//*******************************************************************************************
/**
 * a function to test the start word of the packet. It will check only up to the Bb.length. It should return true so long as the start word is good
 */
static bool preambleCheck(Bb* bb);
/**
 * a function to test the length of the received packet so far. It should return true when enough bytes have been received
 */
static bool lengthCheck(Bb* bb);
/**
 * a function to check the CRC of the received bytes. It will return true with a correct match
 */
static bool crcCheck(Bb* bb);
//*******************************************************************************************
//Code
//*******************************************************************************************

/**
 * Receive n bytes from the queue.
 * If the queue has less than n bytes available, then only use what is available.
 * This is intended for use with a UART
 * This function will test the CRC
 * This function will discard bytes from the queue if they are bad
 * This is implemented with function pointers. I tried to avoid them but it allows easy inclusion into the autogenerated code
 * the length field of the Bb packet field is used as a state variable. Zero indicates the state is reset. After that it indicates how many bytes have been successfully received
 * @param inPacket - the buffer for this packet, also the state of the receive routine
 * @param q - the queue that the new bytes are coming from
 * @param n - the maximum number of bytes to process - this is to limit the type that this routine will take at one calling
 * @return true if a valid packet was received
 *
 */
bool blueberryReceive(Bb* inPacket, ByteQ* q, uint32_t n){
	bool result = false;
	bool fail = false;
	if( inPacket->length == 0){
		inPacket->buffer = q->buffer;
		inPacket->bufferLength = q->bufferSize;
		inPacket->start = q->front;
		inPacket->time = getLocalTimeMillis();
	}
	//figure out how many bytes to receive
	//note that any new bytes will be the difference between the size of bb and the amount on the queue
	uint32_t m = getBytesUsed(q) - inPacket->length;
	if(m > n){
		m = n;
	}

	//cycle through all the bytes so far
	for(uint32_t i = 0; i < m; ++i){

		uint32_t j = ++(inPacket->length);

		if(j < PACKET_LENGTH_INDEX){
			if(!preambleCheck(inPacket)){
				fail = true;
			}
		} else if(lengthCheck(inPacket)){
			if(crcCheck(inPacket)){
				result = true;//we have a valid packet
				break;
				//any remaining bytes should be checked after this packet has been consumed
			} else {
				fail = true;
			}
		}

		if(fail){
			discardFromByteQ(q, inPacket->length);
			inPacket->length = 0;
			inPacket->start = q->front;
		}
	}
	return result;
}
/**
 * Receive all bytes from the queue, or as many as is necessary to receive the packet
 * Assumes that the packet starts at the beginning of the queue
 * This is indended for use with ethernet
 * This function will not test the CRC
 * This function will discard the queue contents if the packet fails the checks
 * This is implemented with function pointers. I tried to avoid them but it allows easy inclusion into the autogenerated code
 * @param inPacket - the buffer for this packet, also the state of the receive routine
 * @param q - the queue that the new bytes are coming from
 * @param n - the maximum number of bytes to process - this is to limit the type that this routine will take at one calling
 * @return true if a valid packet was received
 */
bool blueberryReceiveAll(Bb* inPacket, ByteQ* q){
	bool result = false;
	inPacket->buffer = q->buffer;
	inPacket->bufferLength = q->bufferSize;
	inPacket->start = q->front;
	inPacket->time = getLocalTimeMillis();

	uint32_t n = getBytesUsed(q);
	inPacket->length = n; //this field will eventually be set by the length check
	if(preambleCheck(inPacket)){
		if(lengthCheck(inPacket)){
			result = true;
		}
	}

	if(!result){
		//throw out the queue contents - the packet was no good
		discardFromByteQ(q, n);
		inPacket->length = 0;
	}

	return result;


}
/**
 * Free up data from the byte queue and prep the state
 */
void blueberryReceiveDone(Bb* bb, ByteQ* q){
	discardFromByteQ(q, bb->length);
	bb->time = 0;
	bb->length = 0;//this indicates that the state is reset
	bb->bufferLength = 0;//don't really need to do this
	bb->start = 0;//don't really need to do this
	bb->buffer = NULL;//nor this


}


/**
 * a function to test the start word of the packet. It will check only up to the Bb.length. It should return true so long as the start word is good
 */
static bool preambleCheck(Bb* bb){
		uint32_t a = getBbUint32(bb, 0, PACKET_PREAMBLE_INDEX);
		uint32_t b = PACKET_PREAMBLE;
		uint32_t n = bb->length;
		uint32_t i = n >= 4 ? 0 : 4 - n;
		uint32_t m = 0xffffffff >> (i*8);
		uint32_t r = (a ^ b) & m;
		return r == 0;
}
/**
 * a function to test the length of the received packet so far. It should return true when enough bytes have been received
 */
static bool lengthCheck(Bb* bb){
	uint32_t len = getBbUint16(bb, 0, PACKET_LENGTH_INDEX);
	uint32_t n = bb->length;

	return n >= 6 && n >= len*4;
}
/**
 * a function to check the CRC of the received bytes. It will return true with a correct match
 */
static bool crcCheck(Bb* bb){
	uint32_t n = bb->length;
	uint16_t crcA = (uint16_t)getBbUint16(bb, 0, PACKET_CRC_INDEX);
	uint16_t crcB = computeCrc(bb, PACKET_FIRST_MESSAGE_INDEX, n);
	return crcA == crcB;
}
